import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const regimenesFiscales = [
    { clave: "601", descripcion: "General de Ley Personas Morales" },
    { clave: "603", descripcion: "Personas Morales con Fines no Lucrativos" },
    { clave: "605", descripcion: "Sueldos y Salarios e Ingresos Asimilados a Salarios" },
    { clave: "606", descripcion: "Arrendamiento" },
    { clave: "607", descripcion: "Régimen de Enajenación o Adquisición de Bienes" },
    { clave: "608", descripcion: "Demás ingresos" },
    { clave: "610", descripcion: "Residentes en el Extranjero sin Establecimiento Permanente en México" },
    { clave: "611", descripcion: "Ingresos por Dividendos (socios y accionistas)" },
    { clave: "612", descripcion: "Personas Físicas con Actividades Empresariales y Profesionales" },
    { clave: "614", descripcion: "Ingresos por intereses" },
    { clave: "615", descripcion: "Régimen de los ingresos por obtención de premios" },
    { clave: "616", descripcion: "Sin obligaciones fiscales" },
    { clave: "620", descripcion: "Sociedades Cooperativas de Producción que optan por diferir sus ingresos" },
    { clave: "621", descripcion: "Incorporación Fiscal" },
    { clave: "622", descripcion: "Actividades Agrícolas, Ganaderas, Silvícolas y Pesqueras" },
    { clave: "623", descripcion: "Opcional para Grupos de Sociedades" },
    { clave: "624", descripcion: "Coordinados" },
    { clave: "625", descripcion: "Régimen de las Actividades Empresariales con ingresos a través de Plataformas Tecnológicas" },
    { clave: "626", descripcion: "Régimen Simplificado de Confianza" },
];

const subtiposRemolque = [
    { clave: "CTR001", descripcion: "Caballete" },
    { clave: "CTR002", descripcion: "Caja" },
    { clave: "CTR003", descripcion: "Caja Abierta" },
    { clave: "CTR004", descripcion: "Caja Cerrada" },
    { clave: "CTR005", descripcion: "Caja De Recolección Con Cargador Frontal" },
    { clave: "CTR006", descripcion: "Caja Refrigerada" },
    { clave: "CTR007", descripcion: "Caja Seca" },
    { clave: "CTR008", descripcion: "Caja Transferencia" },
    { clave: "CTR009", descripcion: "Cama Baja o Cuello Ganso" },
    { clave: "CTR010", descripcion: "Chasis Portacontenedor" },
    { clave: "CTR011", descripcion: "Convencional De Chasis" },
    { clave: "CTR012", descripcion: "Equipo Especial" },
    { clave: "CTR013", descripcion: "Estacas" },
    { clave: "CTR014", descripcion: "Góndola Madrina" },
    { clave: "CTR015", descripcion: "Grúa Industrial" },
    { clave: "CTR016", descripcion: "Grúa" },
    { clave: "CTR017", descripcion: "Integral" },
    { clave: "CTR018", descripcion: "Jaula" },
    { clave: "CTR019", descripcion: "Media Redila" },
    { clave: "CTR020", descripcion: "Pallet o Celdillas" },
    { clave: "CTR021", descripcion: "Plataforma" },
    { clave: "CTR022", descripcion: "Plataforma Con Grúa" },
    { clave: "CTR023", descripcion: "Plataforma Encortinada" },
    { clave: "CTR024", descripcion: "Redilas" },
    { clave: "CTR025", descripcion: "Refrigerador" },
    { clave: "CTR026", descripcion: "Revolvedora" },
    { clave: "CTR027", descripcion: "Semicaja" },
    { clave: "CTR028", descripcion: "Tanque" },
    { clave: "CTR029", descripcion: "Tolva" },
    { clave: "CTR031", descripcion: "Volteo" },
    { clave: "CTR032", descripcion: "Volteo Desmontable" },
];

// Catálogo c_ClaveUnidadPeso - SAT Unidades de medida y embalaje
const clavesUnidadPeso = [
    // Contenedores y Embalaje
    { clave: "Tu", nombre: "Contenedor externo" },
    { clave: "X1A", nombre: "Tambor de acero" },
    { clave: "X1B", nombre: "Tambor de aluminio" },
    { clave: "X1D", nombre: "Tambor contrachapado" },
    { clave: "X1F", nombre: "Contenedor flexible" },
    { clave: "X1G", nombre: "Tambor de fibra" },
    { clave: "X1w", nombre: "Tambor de madera" },
    { clave: "X2C", nombre: "Barril de madera" },
    { clave: "X3A", nombre: "Bidón de acero" },
    { clave: "X3H", nombre: "Bidón de plástico" },
    { clave: "X43", nombre: "Bolsa de gran tamaño" },
    { clave: "X44", nombre: "Bolsa de plástico" },
    { clave: "X4A", nombre: "Caja de acero" },
    { clave: "X4B", nombre: "Caja de aluminio" },
    { clave: "X4C", nombre: "Caja de madera natural" },
    { clave: "X4D", nombre: "Caja de contrachapado" },
    { clave: "X4F", nombre: "Caja de madera reconstituida" },
    { clave: "X4G", nombre: "Caja de cartón" },
    { clave: "X4H", nombre: "Caja de plástico" },
    { clave: "X5H", nombre: "Bolsa de plástico tejido" },
    { clave: "X5L", nombre: "Bolsa textil" },
    { clave: "X5M", nombre: "Bolsa de papel" },
    { clave: "X6H", nombre: "Recipiente de plástico, Contenedor compuesto" },
    { clave: "X6P", nombre: "Recipiente de vidrio, Contenedor compuesto" },
    { clave: "X7A", nombre: "Estuche para carro" },
    { clave: "X7B", nombre: "Estuche de madera" },
    { clave: "X8A", nombre: "Pallet de madera" },
    { clave: "X8B", nombre: "Cajón de madera" },
    { clave: "X8C", nombre: "Madera flejada" },
    { clave: "XAA", nombre: "Contenedor intermedio para gráneles de plástico rígido" },
    { clave: "XAB", nombre: "Contenedor de fibra" },
    { clave: "XAC", nombre: "Contenedor de papel" },
    { clave: "XAD", nombre: "Contenedor de madera" },
    { clave: "XAE", nombre: "Aerosol" },
    { clave: "XAF", nombre: "Pallet modular con collares, 80cms * 60cms" },
    { clave: "XAG", nombre: "Pallet o empaquetado" },
    { clave: "XAH", nombre: "Pallet, 100cms X 110cms" },
    { clave: "XAI", nombre: "Contenedor tipo concha" },
    { clave: "XAJ", nombre: "Cono" },
    { clave: "XAL", nombre: "Esfera" },
    { clave: "XAM", nombre: "Ampolleta no protegida" },
    { clave: "XAP", nombre: "Ampolleta protegida" },
    { clave: "XAT", nombre: "Atomizador" },
    { clave: "XAV", nombre: "Cápsula" },
    { clave: "XB4", nombre: "Cinturón" },
    { clave: "XBA", nombre: "Barril" },
    { clave: "XBB", nombre: "Bobina" },
    { clave: "XBC", nombre: "Cajón para botellas / Estante para botellas" },
    { clave: "XBD", nombre: "Tablero" },
    { clave: "XBE", nombre: "Flejado" },
    { clave: "XBF", nombre: "Globo no protegido" },
    { clave: "XBG", nombre: "Bolso" },
    { clave: "XBH", nombre: "Manojo" },
    { clave: "XBI", nombre: "Compartimiento" },
    { clave: "XBJ", nombre: "Cubeta" },
    { clave: "XBK", nombre: "Cesta" },
    { clave: "XBL", nombre: "Paca comprimida" },
    { clave: "XBM", nombre: "Cuenco" },
    { clave: "XBN", nombre: "Paca no comprimida" },
    { clave: "XBO", nombre: "Botella no-protegida y cilíndrica" },
    { clave: "XBP", nombre: "Globo protegido" },
    { clave: "XBQ", nombre: "Botella cilíndrica protegida" },
    { clave: "XBR", nombre: "Barra" },
    { clave: "XBS", nombre: "Botella, no-protegida en forma de bulbo" },
    { clave: "XBT", nombre: "Rollo de tela" },
    { clave: "XBU", nombre: "Butt" },
    { clave: "XBV", nombre: "Botella de bulbo protegido" },
    { clave: "XBW", nombre: "Caja para líquidos" },
    { clave: "XBX", nombre: "Caja" },
    { clave: "XBY", nombre: "Tablero, con fleje/ agrupados/ armados" },
    { clave: "XBZ", nombre: "Barras, con fleje/ agrupados/ armados" },
    { clave: "XCA", nombre: "Lata rectangular" },
    { clave: "XCB", nombre: "Cajón para cerveza" },
    { clave: "XCC", nombre: "Mantequera" },
    { clave: "XCD", nombre: "Lata con mango y boquilla" },
    { clave: "XCE", nombre: "Cesto tejido" },
    { clave: "XCF", nombre: "Cofre" },
    { clave: "XCG", nombre: "Contenedor tipo Jaula" },
    { clave: "XCH", nombre: "Cajonera" },
    { clave: "XCI", nombre: "Frasco" },
    { clave: "XCJ", nombre: "Ataúd" },
    { clave: "XCK", nombre: "Barrica" },
    { clave: "XCL", nombre: "Espiral" },
    { clave: "XCM", nombre: "Paquete de tarjetas" },
    { clave: "XCN", nombre: "Contenedor, no especificado como equipo de transporte" },
    { clave: "XCO", nombre: "Garrafón no protegido" },
    { clave: "XCP", nombre: "Garrafón protegido" },
    { clave: "XCQ", nombre: "Cartucho" },
    { clave: "XCR", nombre: "Cajón" },
    { clave: "XCS", nombre: "Estuche" },
    { clave: "XCT", nombre: "Cartón" },
    { clave: "XCU", nombre: "Vaso" },
    { clave: "XCV", nombre: "Cubierta" },
    { clave: "XCW", nombre: "Jaula estilo rodillo" },
    { clave: "XCX", nombre: "Lata cilíndrica" },
    { clave: "XCY", nombre: "Cilindro" },
    { clave: "XCZ", nombre: "Lona" },
    { clave: "XDA", nombre: "Cajón multicapa de plástico" },
    { clave: "XDB", nombre: "Cajón de varias capas de madera" },
    { clave: "XDC", nombre: "Cajón multicapa de cartón" },
    { clave: "XDG", nombre: "Jaula, Según la clasificación de la compañía (CHEP)" },
    { clave: "XDH", nombre: "Caja, Según la clasificación de la compañía (CHEP), Eurobox" },
    { clave: "XDI", nombre: "Tambor de hierro" },
    { clave: "XDJ", nombre: "Damajuana o garrafa, no protegido" },
    { clave: "XDK", nombre: "Cajón a granel, cartón" },
    { clave: "XDL", nombre: "Cajas de plástico" },
    { clave: "XDM", nombre: "Cajones a granel de madera" },
    { clave: "XDN", nombre: "Dispensador" },
    { clave: "XDP", nombre: "Damajuana o garrafa, protegido" },
    { clave: "XDR", nombre: "Tambor" },
    { clave: "XDS", nombre: "Bandeja de una capa sin cubierta y de plástico" },
    { clave: "XDT", nombre: "Bandeja de una capa sin cubierta y de madera" },
    { clave: "XDU", nombre: "Bandeja de una capa sin cubierta y poliestireno" },
    { clave: "XDV", nombre: "Bandeja de una capa sin cubierta y de cartón" },
    { clave: "XDW", nombre: "Bandeja de dos capas sin tapa y con bandeja de plástico" },
    { clave: "XDX", nombre: "Bandeja de dos capas sin cubierta y de madera" },
    { clave: "XDY", nombre: "Bandeja de dos capas sin cubierta y de cartón" },
    { clave: "XEC", nombre: "Bolsa de plástico" },
    { clave: "XED", nombre: "Estuche, con pallet de base" },
    { clave: "XEE", nombre: "Estuche, con pallet base de madera" },
    { clave: "XEF", nombre: "Estuche, con pallet base de cartón" },
    { clave: "XEG", nombre: "Estuche, con pallet base de plástico" },
    { clave: "XEH", nombre: "Estuche, con pallet base de metal" },
    { clave: "XEI", nombre: "Estuche isotérmico" },
    { clave: "XEN", nombre: "Sobre" },
    { clave: "XFB", nombre: "Bolsa flexible" },
    { clave: "XFC", nombre: "Cajón para fruta" },
    { clave: "XFD", nombre: "Cajón enmarcado" },
    { clave: "XFE", nombre: "Tanque flexible" },
    { clave: "XFI", nombre: "Firkin" },
    { clave: "XFL", nombre: "Matraz" },
    { clave: "XFO", nombre: "Cajón para zapatos" },
    { clave: "XFP", nombre: "Caja auxiliar para película fotográfica" },
    { clave: "XFR", nombre: "Marco" },
    { clave: "XFT", nombre: "Contenedor para alimentos" },
    { clave: "XFW", nombre: "Carro de cama plana" },
    { clave: "XFX", nombre: "Bolsa flexible tipo contenedor" },
    { clave: "XGB", nombre: "Botella para gas" },
    { clave: "XGI", nombre: "Viga" },
    { clave: "XGL", nombre: "Contenedor tipo galón" },
    { clave: "XGR", nombre: "Recipiente de vidrio" },
    { clave: "XGU", nombre: "Bandeja contenedor para apilar horizontalmente objetos planos" },
    { clave: "XGY", nombre: "Costal de Yute" },
    { clave: "XGZ", nombre: "Vigas con correas o agrupadas" },
    { clave: "XHA", nombre: "Cesta con mango y de plástico" },
    { clave: "XHB", nombre: "Cesta con mango y de madera" },
    { clave: "XHC", nombre: "Cesta con asa y de cartón" },
    { clave: "XHG", nombre: "Hogshead" },
    { clave: "XHN", nombre: "Gancho" },
    { clave: "XHR", nombre: "Cesto" },
    { clave: "XIA", nombre: "Paquete con pantalla y de madera" },
    { clave: "XIB", nombre: "Paquete con pantalla y de cartón" },
    { clave: "XIC", nombre: "Paquete con pantalla y de plástico" },
    { clave: "XID", nombre: "Paquete con pantalla y de metal" },
    { clave: "XIE", nombre: "Paquete de mostrador" },
    { clave: "XIF", nombre: "Envase para alimentos" },
    { clave: "XIG", nombre: "Paquete envuelto en papel" },
    { clave: "XIH", nombre: "Tambor de plástico" },
    { clave: "XIK", nombre: "Paquete de cartón con los agujeros para botellas" },
    { clave: "XIL", nombre: "Bandeja rígida con tapa y apilable (CEN TS 14482: 2002)" },
    { clave: "XIN", nombre: "Lingote" },
    { clave: "XIZ", nombre: "Lingotes con correas/ agrupados" },
    { clave: "XJB", nombre: "Bolsa jumbo" },
    { clave: "XJC", nombre: "Bidón rectangular" },
    { clave: "XJG", nombre: "Jarra" },
    { clave: "XJR", nombre: "Tarro" },
    { clave: "XJT", nombre: "Bolsa de yute" },
    { clave: "XJY", nombre: "Bidón, cilíndrico" },
    { clave: "XKG", nombre: "Barrilete" },
    { clave: "XKI", nombre: "Kit (Conjunto de piezas)" },
    { clave: "XLE", nombre: "Valijas" },
    { clave: "XLG", nombre: "Bitácora" },
    { clave: "XLT", nombre: "Lote" },
    { clave: "XLU", nombre: "Caja de arrastre" },
    { clave: "XLV", nombre: "Contenedor pequeño" },
    { clave: "XLZ", nombre: "Registros con fleje/ agrupados/ armados" },
    { clave: "XMA", nombre: "Cajón metálico" },
    { clave: "XMB", nombre: "Múltiplo de bolsas" },
    { clave: "XMC", nombre: "Cajón para leche" },
    { clave: "XME", nombre: "Contenedor de metal" },
    { clave: "XMR", nombre: "Recipiente de metal" },
    { clave: "XMS", nombre: "Saco milti-pared" },
    { clave: "XMT", nombre: "Tapete" },
    { clave: "XMW", nombre: "Contenedor envuelto en plástico" },
    { clave: "XMX", nombre: "Caja pequeña de cerillos" },
    { clave: "XNA", nombre: "No disponible" },
    { clave: "XNE", nombre: "Sin empaque o no empaquetado" },
    { clave: "XNF", nombre: "Sin empaque o no empaquetado, unidad simple" },
    { clave: "XNG", nombre: "Sin empaque o no empaquetado, unidades múltiples" },
    { clave: "XNS", nombre: "Caja nido" },
    { clave: "XNT", nombre: "Red" },
    { clave: "XNU", nombre: "Red de plástico con tubo" },
    { clave: "XNV", nombre: "Red textil con tubo" },
    { clave: "XOA", nombre: "Pallet, CHEP 40 cm x 60 cm" },
    { clave: "XOB", nombre: "Pallet, CHEP 80 cm x 120 cm" },
    { clave: "XOC", nombre: "Pallet, CHEP 100 cm x 120 cm" },
    { clave: "XOD", nombre: "Pallet, AS 4068-1993" },
    { clave: "XOE", nombre: "Pallet, ISO T11" },
    { clave: "XOF", nombre: "Plataforma, peso o dimensión no especificada" },
    { clave: "XOK", nombre: "Bloque" },
    { clave: "XOT", nombre: "Octabin" },
    { clave: "XP2", nombre: "Charola" },
    { clave: "XPA", nombre: "Cajetilla" },
    { clave: "XPB", nombre: "Pallet, Caja combinada y abierta con caja y pallet" },
    { clave: "XPC", nombre: "Paquete postal" },
    { clave: "XPD", nombre: "Pallet modular con collares (80cms * 100cms)" },
    { clave: "XPE", nombre: "Pallet modular con collares (80cms * 120cms)" },
    { clave: "XPF", nombre: "Corral" },
    { clave: "XPG", nombre: "Placa" },
    { clave: "XPH", nombre: "Cantaro" },
    { clave: "XPI", nombre: "Pleca" },
    { clave: "XPJ", nombre: "Canastilla" },
    { clave: "XPK", nombre: "Paquete" },
    { clave: "XPL", nombre: "Balde" },
    { clave: "XPN", nombre: "Tablón" },
    { clave: "XPO", nombre: "Bolsa pequeña" },
    { clave: "XPR", nombre: "Contenedor de plástico" },
    { clave: "XPT", nombre: "Maceta" },
    { clave: "XPU", nombre: "Cacerola" },
    { clave: "XPV", nombre: "Tubos, con fleje/ agrupados/ armados" },
    { clave: "XPX", nombre: "Pallet" },
    { clave: "XPY", nombre: "Placas con fleje/ agrupados/ armados" },
    { clave: "XPZ", nombre: "Tablones con fleje/ agrupados/ armados" },
    { clave: "XQA", nombre: "Tambor de acero con cabeza no desmontable" },
    { clave: "XQB", nombre: "Tambor de acero con cabeza extraíble" },
    { clave: "XQC", nombre: "Tambor de aluminio con cabeza no extraíble" },
    { clave: "XQD", nombre: "Tambor de aluminio con cabeza extraíble" },
    { clave: "XQF", nombre: "Tambor, plástico con cabeza no desmontable" },
    { clave: "XQG", nombre: "Tambor, plástico, cabeza extraíble" },
    { clave: "XQH", nombre: "Barril de madera con tapón" },
    { clave: "XQJ", nombre: "Barril de madera con cabeza desprendible" },
    { clave: "XQK", nombre: "Bidón de acero con cabeza no desmontable" },
    { clave: "XQL", nombre: "Bidón de acero con cabeza desmontable" },
    { clave: "XQM", nombre: "Bidón de plástico con cabeza no desmontable" },
    { clave: "XQN", nombre: "Bidón de plástico con cabeza extraíble" },
    { clave: "XQP", nombre: "Caja de madera natural estándar" },
    { clave: "XQQ", nombre: "Caja de madera natural con muros a prueba de filtraciones" },
    { clave: "XQR", nombre: "Caja de plástico expandida" },
    { clave: "XQS", nombre: "Caja de plástico sólida" },
    { clave: "XRD", nombre: "Rod" },
    { clave: "XRG", nombre: "Anillo" },
    { clave: "XRJ", nombre: "Estante, Perchero para ropa" },
    { clave: "XRK", nombre: "Estante" },
    { clave: "XRL", nombre: "Carrete" },
    { clave: "XRO", nombre: "Rollo" },
    { clave: "XRT", nombre: "Red Roja" },
    { clave: "XRZ", nombre: "Varillas con fleje/ agrupados/ armados" },
    { clave: "XSA", nombre: "Saco" },
    { clave: "XSB", nombre: "Losa" },
    { clave: "XSC", nombre: "Cajón poco profundo" },
    { clave: "XSD", nombre: "Huso" },
    { clave: "XSE", nombre: "Baúl" },
    { clave: "XSH", nombre: "Bolsa pequeña hermética" },
    { clave: "XSI", nombre: "Patín" },
    { clave: "XSK", nombre: "Carcasa esqueleto" },
    { clave: "XSL", nombre: "Hoja de deslizamiento" },
    { clave: "XSM", nombre: "Hoja de metal" },
    { clave: "XSO", nombre: "Carrete pequeño" },
    { clave: "XSP", nombre: "Hoja de empaque de plástico" },
    { clave: "XSS", nombre: "Cajón de acero" },
    { clave: "XSU", nombre: "Maleta" },
    { clave: "XSV", nombre: "Sobre de acero" },
    { clave: "XSW", nombre: "Envoltorio" },
    { clave: "XSY", nombre: "Manga" },
    { clave: "XSZ", nombre: "Hojas con fleje/ agrupados/ armados" },
    { clave: "XT1", nombre: "Tableta" },
    { clave: "XTB", nombre: "Tina" },
    { clave: "XTC", nombre: "Caja para té" },
    { clave: "XTD", nombre: "Tubo plegable" },
    { clave: "XTG", nombre: "Contenedor de tanque genérico" },
    { clave: "XTI", nombre: "Tierce" },
    { clave: "XTK", nombre: "Tanque rectangular" },
    { clave: "XTL", nombre: "Tina con tapa" },
    { clave: "XTN", nombre: "Hojalata" },
    { clave: "XTO", nombre: "Tonel" },
    { clave: "XTR", nombre: "Maletero" },
    { clave: "XTS", nombre: "Estructura" },
    { clave: "XTT", nombre: "Bolsa de mano" },
    { clave: "XTU", nombre: "Tubo" },
    { clave: "XTV", nombre: "Tubo con boquilla" },
    { clave: "XTW", nombre: "Pallet tricapa" },
    { clave: "XTY", nombre: "Tanque cilíndrico" },
    { clave: "XTZ", nombre: "Tubos con fleje/ agrupados/ armados" },
    { clave: "XUC", nombre: "Sin empaque" },
    { clave: "XUN", nombre: "Unidad" },
    { clave: "XVA", nombre: "Tanque" },
    { clave: "XVG", nombre: "Tanque de gas (a 1,031 mbar y 15° C)" },
    { clave: "XVI", nombre: "Frasco pequeño" },
    { clave: "XVK", nombre: "Paquete transportable" },
    { clave: "XVL", nombre: "Contenedor para líquidos a granel" },
    { clave: "XVN", nombre: "Vehículo" },
    { clave: "XVO", nombre: "Contenedor para sólido de partículas grandes a granel (nódulos)" },
    { clave: "XVP", nombre: "Envasado al vacío" },
    { clave: "XVQ", nombre: "Tanque para Gas licuado (a temperatura / presión anormal)" },
    { clave: "XVR", nombre: "Contenedor para sólidos de partículas granulares a granel (Granos)" },
    { clave: "XVS", nombre: "Contenedor de chatarra a granel" },
    { clave: "XVY", nombre: "Contenedor para sólido de partículas finas a granel (polvos)" },
    { clave: "XWA", nombre: "Contenedor de granel intermedio" },
    { clave: "XWB", nombre: "Botella de mimbre" },
    { clave: "XWC", nombre: "Contenedor intermedio para gráneles y de acero" },
    { clave: "XWD", nombre: "Contenedor intermedio para gráneles y de aluminio" },
    { clave: "XWF", nombre: "Contenedor intermedio para gráneles y de metal" },
    { clave: "XWG", nombre: "Contenedor intermedio para gráneles y de acero presurizado menor a 10 kpa" },
    { clave: "XWH", nombre: "Contenedor intermedio para gráneles y de aluminio, presurizado menor a 10 kpa" },
    { clave: "XWJ", nombre: "Contenedor intermedio para gráneles y de metal con una presión de 10 kpa" },
    { clave: "XWK", nombre: "Contenedor intermedio para gráneles y de acero para líquido" },
    { clave: "XWL", nombre: "Contenedor intermedio para gráneles y de aluminio para líquido" },
    { clave: "XWM", nombre: "Contenedor intermedio para gráneles y de metal para líquido" },
    { clave: "XWN", nombre: "Contenedor intermedio para gráneles con tejido plástico sin capa con revestimiento" },
    { clave: "XWP", nombre: "Contenedor intermedio para gráneles con tejido plástico y recubierto" },
    { clave: "XWQ", nombre: "Contenedor intermedio para gráneles con tejido plástico con revestimiento" },
    { clave: "XWR", nombre: "Contenedor intermedio para gráneles con tejido plástico, revestido y con forro" },
    { clave: "XWS", nombre: "Contenedor intermedio para gráneles con película de plástico" },
    { clave: "XWT", nombre: "Contenedor intermedio para gráneles textil sin capa / forro" },
    { clave: "XWU", nombre: "Contenedor intermedio para gráneles de madera natural con forro interior" },
    { clave: "XWV", nombre: "Contenedor intermedio para gráneles textil recubierto" },
    { clave: "XWW", nombre: "Contenedor intermedio para gráneles textil con revestimiento" },
    { clave: "XWX", nombre: "Contenedor intermedio para gráneles textil recubierto y con forro" },
    { clave: "XWY", nombre: "Contenedor intermedio para gráneles contrachapado con revestimiento interior" },
    { clave: "XWZ", nombre: "Contenedor intermedio para gráneles de madera reconstituida con revestimiento interior" },
    { clave: "XXA", nombre: "Bolsa de tejido plástico, sin abrigo interior ni forro" },
    { clave: "XXB", nombre: "Bolsa de tejido plástico a prueba de filtraciones" },
    { clave: "XXC", nombre: "Bolsa de tejido plástico resistente al agua" },
    { clave: "XXD", nombre: "Bolsa con película de plástico" },
    { clave: "XXF", nombre: "Bolsa textil sin capa ni forro interior" },
    { clave: "XXG", nombre: "Bolsa textil a prueba de filtraciones" },
    { clave: "XXH", nombre: "Bolsa textil resistente al agua" },
    { clave: "XXJ", nombre: "Bolsa de papel multi-pared" },
    { clave: "XXK", nombre: "Bolsa de papel multi-pared, resistente al agua" },
    { clave: "XYA", nombre: "Empaque compuesto, recipiente de plástico en tambor de acero" },
    { clave: "XYB", nombre: "Empaque compuesto, recipiente de plástico en cajas de acero" },
    { clave: "XYC", nombre: "Empaque compuesto, recipiente de plástico en tambor de aluminio" },
    { clave: "XYD", nombre: "Empaque compuesto, recipiente de plástico en cajón de aluminio" },
    { clave: "XYF", nombre: "Empaque compuesto, recipiente de plástico en caja de madera" },
    { clave: "XYG", nombre: "Empaque compuesto, recipiente de plástico en tambor de madera contrachapada" },
    { clave: "XYH", nombre: "Empaque compuesto, recipiente de plástico en caja de madera contrachapada" },
    { clave: "XYJ", nombre: "Empaque compuesto, recipiente de plástico en tambor de fibra" },
    { clave: "XYK", nombre: "Empaque compuesto, recipiente de plástico en caja de cartón" },
    { clave: "XYL", nombre: "Empaque compuesto, recipiente de plástico en el tambor de plástico" },
    { clave: "XYM", nombre: "Empaque compuesto, recipiente de plástico en caja de plástico sólido" },
    { clave: "XYN", nombre: "Empaque compuesto, receptáculo de vidrio en tambor de acero" },
    { clave: "XYP", nombre: "Empaque compuesto, receptáculo de vidrio en caja de cajas de acero" },
    { clave: "XYQ", nombre: "Empaque compuesto, recipiente de vidrio en tambor de aluminio" },
    { clave: "XYR", nombre: "Empaque compuesto, receptáculo de vidrio en caja de aluminio" },
    { clave: "XYS", nombre: "Empaque compuesto, recipiente de vidrio en caja de madera" },
    { clave: "XYT", nombre: "Empaque compuesto, recipiente de vidrio en tambor de madera contrachapada" },
    { clave: "Xyv", nombre: "Empaque compuesto, recipiente de vidrio en el cesto de mimbre" },
    { clave: "XYW", nombre: "Empaque compuesto, recipiente de vidrio en tambor de fibra" },
    { clave: "XYX", nombre: "Empaque compuesto, recipiente de vidrio en caja de cartón" },
    { clave: "XYY", nombre: "Empaque compuesto, recipiente de vidrio en paquete de plástico expandible" },
    { clave: "XYZ", nombre: "Empaque compuesto, recipiente de vidrio en paquete de plástico sólido" },
    { clave: "XZA", nombre: "Contenedor de granel intermedio, papel, multi-pared" },
    { clave: "XZB", nombre: "Bolsa grande" },
    { clave: "XZC", nombre: "Contenedor intermedio para gráneles de papel, multi-pared y resistente al agua" },
    { clave: "XZD", nombre: "Contenedor intermedio para gráneles de plástico rígido, con equipo estructural para sólidos" },
    { clave: "XZF", nombre: "Contenedor intermedio para gráneles de plástico rígido, autoportante para sólidos" },
    { clave: "XZG", nombre: "Contenedor intermedio para gráneles de plástico rígido, con equipo estructural, presurizado" },
    { clave: "XZH", nombre: "Contenedor intermedio para gráneles de plástico rígido, autoportante y presurizado" },
    { clave: "XZJ", nombre: "Contenedor intermedio para gráneles de plástico rígido, con equipo estructural para líquidos" },
    { clave: "XZK", nombre: "Contenedor intermedio para gráneles de plástico rígido, autoportante, líquidos" },
    { clave: "XZL", nombre: "Contenedor intermedio para gráneles, compuesto y de plástico rígido, sólidos" },
    { clave: "XZM", nombre: "Contenedor intermedio para gráneles, compuesto y de plástico flexible, sólidos" },
    { clave: "XZN", nombre: "Contenedor intermedio para gráneles, compuesto y de plástico rígido, presurizado" },
    { clave: "XZP", nombre: "Contenedor intermedio para gráneles, compuesto y de plástico flexible, presurizado" },
    { clave: "XZQ", nombre: "Contenedor intermedio para gráneles, compuesto y de plástico rígido, líquidos" },
    { clave: "XZR", nombre: "Contenedor intermedio para gráneles, compuesto y de plástico flexible para líquidos" },
    { clave: "XZS", nombre: "Contenedor intermedio para gráneles, compuesto" },
    { clave: "XZT", nombre: "Contenedor intermedio para gráneles con tablero de fibras" },
    { clave: "XZU", nombre: "Contenedor intermedio para gráneles flexible" },
    { clave: "XZV", nombre: "Contenedor intermedio para gráneles de metal, distinto del acero" },
    { clave: "XZW", nombre: "Contenedor intermedio para gráneles, de madera natural" },
    { clave: "XZX", nombre: "Contenedor intermedio para gráneles, de contrachapado" },
    { clave: "XZY", nombre: "Contenedor intermedio para gráneles, de madera reconstituida" },
    // Unidades de Masa/Peso
    { clave: "KGM", nombre: "Kilogramo" },
    { clave: "MC", nombre: "Microgramo" },
    { clave: "DJ", nombre: "Decagramo" },
    { clave: "DG", nombre: "Decigramo" },
    { clave: "GRM", nombre: "Gramo" },
    { clave: "CGM", nombre: "Centigramo" },
    { clave: "TNE", nombre: "Tonelada (tonelada métrica)" },
    { clave: "DTN", nombre: "Decitonelada métrica" },
    { clave: "MGM", nombre: "Miligramo" },
    { clave: "HGM", nombre: "Hectogramo" },
    { clave: "KTN", nombre: "Kilotonelada Métrica" },
    { clave: "2U", nombre: "Megagramo" },
    { clave: "LBR", nombre: "Libra" },
    { clave: "GRN", nombre: "Grano" },
    { clave: "ONZ", nombre: "Onza (avoirdupois)" },
    { clave: "CWI", nombre: "Hundredweight" },
    { clave: "CWA", nombre: "Hundred pound" },
    { clave: "LTN", nombre: "Tonelada (UK) o tonelada larga" },
    { clave: "STI", nombre: "Estone (UK)" },
    { clave: "STN", nombre: "Tonelada (estados unidos) o tonelada corta" },
    { clave: "APZ", nombre: "Onza troy u onza farmacéutica" },
    { clave: "F13", nombre: "Slug" },
    { clave: "K64", nombre: "Libra (avoirdupois) por grado fahrenheit" },
    { clave: "L69", nombre: "Tonelada por kelvin" },
    { clave: "L87", nombre: "Tonelada corta por grado fahrenheit" },
    { clave: "M85", nombre: "Tonelada, ensayo" },
    { clave: "M86", nombre: "Libra Alemana" },
    { clave: "J33", nombre: "Microgramo por kilogramo" },
    { clave: "L32", nombre: "Nanogramo por kilogramo" },
    { clave: "NA", nombre: "Miligramo por kilogramo" },
    { clave: "M29", nombre: "Kilogramo por kilogramo" },
    { clave: "M91", nombre: "Libra por libra" },
    { clave: "Q29", nombre: "Microgramo por hectogramo" },
    // Unidades de Volumen
    { clave: "MTQ", nombre: "Metro cúbico" },
    { clave: "MAL", nombre: "Megalitro" },
    { clave: "LTR", nombre: "Litro" },
    { clave: "MMQ", nombre: "Milímetro cúbico" },
    { clave: "CMQ", nombre: "Centímetro cúbico" },
    { clave: "DMQ", nombre: "Decímetro cúbico" },
    { clave: "MLT", nombre: "Mililitro" },
    { clave: "HLT", nombre: "Hectolitro" },
    { clave: "CLT", nombre: "Centilitro" },
    { clave: "DMA", nombre: "Decámetro cúbico" },
    { clave: "H19", nombre: "Hectómetro cúbico" },
    { clave: "H20", nombre: "Kilómetro cúbico" },
    { clave: "M71", nombre: "Metro cúbico por pascal (joules)" },
    { clave: "DLT", nombre: "Decilitro" },
    { clave: "4G", nombre: "Microlitro" },
    { clave: "K6", nombre: "Kilolitro" },
    { clave: "A44", nombre: "Decalitro" },
    { clave: "G94", nombre: "Centímetro cúbico por bar" },
    { clave: "G95", nombre: "Litro por bar" },
    { clave: "G96", nombre: "Metro cúbico por bar" },
    { clave: "G97", nombre: "Mililitro por bar" },
    { clave: "5I", nombre: "Pies cúbicos estándar" },
    { clave: "INQ", nombre: "Pulgada cúbica" },
    { clave: "FTQ", nombre: "Pie cúbico" },
    { clave: "YDQ", nombre: "Yarda cúbica" },
    { clave: "GLI", nombre: "Galón (UK)" },
    { clave: "GLL", nombre: "Galón (EUA)" },
    { clave: "PT", nombre: "Pinta (US)" },
    { clave: "PTI", nombre: "Pint (uk)" },
    { clave: "QTI", nombre: "Cuarto (UK)" },
    { clave: "PTL", nombre: "Pinta líquida (estados unidos)" },
    { clave: "QTL", nombre: "Cuarto de líquido (estados unidos)" },
    { clave: "PTD", nombre: "Pinta seca (estados unidos)" },
    { clave: "OZI", nombre: "Onza líquida (UK)" },
    { clave: "QT", nombre: "Cuarto (EUA)" },
    { clave: "J57", nombre: "Barril (uk petróleo)" },
    { clave: "K21", nombre: "Pie cúbico por grado fahrenheit" },
    { clave: "K23", nombre: "Pie cúbico por psi" },
    { clave: "L43", nombre: "Peck (UK)" },
    { clave: "L61", nombre: "Pinta (US seco)" },
    { clave: "L62", nombre: "Cuarto de galón (seco de los EUA)" },
    { clave: "L84", nombre: "Tonelada (flota UK)" },
    { clave: "L86", nombre: "Tonelada (flota estados unidos)" },
    { clave: "M11", nombre: "Yarda cúbica por grado fahrenheit" },
    { clave: "M14", nombre: "Yarda cúbica por psi" },
    { clave: "OZA", nombre: "Onza líquida (estados unidos)" },
    { clave: "BUI", nombre: "Bushel (UK)" },
    { clave: "BUA", nombre: "Bushel (EUA)" },
    { clave: "BLL", nombre: "Barril (EUA)" },
    { clave: "BLD", nombre: "Barril seco (EUA)" },
    { clave: "GLD", nombre: "Galón seco (EUA)" },
    { clave: "QTD", nombre: "Cuarto seco (estados unidos)" },
    { clave: "G26", nombre: "Estere" },
    { clave: "G21", nombre: "Taza (unidad de volumen)" },
    { clave: "G24", nombre: "Cucharada (estados unidos)" },
    { clave: "G25", nombre: "Cucharilla (estados unidos)" },
    { clave: "G23", nombre: "Peck" },
    { clave: "M67", nombre: "Acre-pie" },
    { clave: "M68", nombre: "Cordón" },
    { clave: "M69", nombre: "Milla cúbica (reino unido)" },
    { clave: "M70", nombre: "Unidad tradicional de capacidad de carga" },
    { clave: "Q32", nombre: "Femtolitro" },
    { clave: "Q33", nombre: "Picolitro" },
    { clave: "Q34", nombre: "Nanolitro" },
    { clave: "NM3", nombre: "Metro cúbico normalizado" },
    { clave: "SM3", nombre: "Metro cúbico estándar" },
];

async function main() {
    console.log('🌱 Seeding regímenes fiscales...');

    for (const regimen of regimenesFiscales) {
        await prisma.regimenFiscal.upsert({
            where: { clave: regimen.clave },
            update: { descripcion: regimen.descripcion },
            create: regimen,
        });
    }

    console.log('✅ Regímenes fiscales seeded successfully!');

    console.log('🌱 Seeding subtipos de remolque...');

    for (const subtipo of subtiposRemolque) {
        await prisma.subtipoRemolque.upsert({
            where: { clave: subtipo.clave },
            update: { descripcion: subtipo.descripcion },
            create: subtipo,
        });
    }

    console.log('✅ Subtipos de remolque seeded successfully!');

    console.log('🌱 Seeding claves de unidad de peso...');

    for (const unidad of clavesUnidadPeso) {
        await prisma.claveUnidadPeso.upsert({
            where: { clave: unidad.clave },
            update: { nombre: unidad.nombre },
            create: unidad,
        });
    }

    console.log('✅ Claves de unidad de peso seeded successfully!');
}

main()
    .catch((e) => {
        console.error('Error seeding database:', e);
        process.exit(1);
    })
    .finally(async () => {
        await prisma.$disconnect();
    });
